# Мир, в котором находится хаб.
world_name: "world"

# Центральная точка хаба (X Y Z Yaw Pitch).
# Сюда телепортирует игрока при входе и падении.
world_center: "0.5 160.0 0.5 90.0 -25.0"

# Высота по Y. Если игрок опустится ниже этого уровня, он будет телепортирован в центр хаба.
void_fall_y_level: 70
