name: ShardplexHubManager
version: 1.0
main: com.shardclay.shardplexhubmanager.ShardplexHubManager
api-version: 1.20
author: Shardclay
commands:
  shm:
    description: Main command for ShardplexHubManager
    usage: /<command> [reload]
permissions:
  shardplex.shm.reload:
    description: Allows reloading the plugin's configuration.
    default: op
